# Instruction refer:https://docs.docker.com/language/golang/build-images/
# Ubuntu-golang :https://github.com/jheise/ubuntu-golang

# Images from: https://hub.docker.com/_/golang
## Build the application from source
#FROM golang:1.21 AS build-stage
FROM golang:1.21    

# Set destination for COPY
WORKDIR /app

# Copy the source code. Note the slash at the end, as explained in
# https://docs.docker.com/engine/reference/builder/#copy
COPY . .
RUN pwd
#RUN yarn install --production
RUN apt-get update && apt-get install -y

# Build
RUN cd scripts && bash build_MacOS.sh


# Optional:
# To bind to a TCP port, runtime parameters must be supplied to the docker command.
# But we can document in the Dockerfile what ports
# the application is going to listen on by default.
# https://docs.docker.com/engine/reference/builder/#expose
EXPOSE 8080

# Run
SHELL ["/bin/bash", "-c"]
#SHELL ["/bin/bash", "/app/build/package/runsurvey.sh"]

#ENTRYPOINT ["/bin/bash"]